### ISSUE TITLE
Archive should return record

### ISSUE THREAD

**Issue by jebukowski** [endfire/redink#13]
Currently, archiving a record returns either { deleted: true, id } or { deleted: false } for a successful or unsuccessful deletion, respectively. 

It would be very helpful if only the record was returned so that it could potentially be normalized/flattened.

**Comment by calvinbrewer** [comment]
Archiving a record: 

``` javascript
// request
archive('company', '1');

// response
{
  id: '1',
  name: 'Google',
  url: 'www.google.com',
  meta: {
    archived: false,
  },
}
```

**Comment by dylnslck** [comment]
@calvinbrewer 

The relationships are side-loaded like normal, right?

**Comment by calvinbrewer** [comment]
@dylnslck 

Correct:

``` javascript
// archive record with relationships
archive('animal', '1');

// response 
{
  id: '1',
  name: 'Snickers',
  type: 'cat',
  owner: {
    id: '2',
    name: 'CJ',
    animals: ['1', '2'],
    meta: {
      archived: false,
    },
  },
  meta: {
    archived: true
  },
}
```
